bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

homepage/urls.py
from django.urls import path, include
from .views import index, contacts, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, \
    BBPasswordChangeView, RegisterUserView, RegisterDoneView, user_activate

app_name = 'homepage'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('about/', contacts, name='about'),
    path('', index, name='index'),
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal


from .utilities import send_activation_notification
# Create your models here.


class MainUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Оповещения отсылать?')

    class Meta(AbstractUser.Meta):
        pass


user_registrated = Signal(providing_args=['instance'])

def iser_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])

user_registrated.connect(iser_registrated_dispatcher)

homepage/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import MainUser, user_registrated


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')

    class Meta:
        model = MainUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation._password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно', widget=forms.PasswordInput,
                                help_text='Введите пароль повторно')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введеные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = MainUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')

homepage/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature


from .models import MainUser
from .forms import ChangeUserInfoForm, RegisterUserForm
from .utilities import signer
# Create your views here.
# Контроллер-функция, которая возвращает нам базовую страницу из папки шаблонов


def index(request):
    return render(request, 'basic.html',)


def contacts(request):
    return render(request, 'homepage/about.html',)

class BBLoginView(LoginView):
    template_name = 'homepage/profile_tmp/login.html'

@login_required
def profile(request):
    return render(request, 'homepage/profile_tmp/profile.html')

class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'homepage/profile_tmp/logout.html'

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = MainUser
    template_name = 'homepage/profile_tmp/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('homepage:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'homepage/profile_tmp/password_change.html'
    success_url = reverse_lazy('homepage:profile')
    success_message = 'Пароль изменён успешно'


class RegisterUserView(CreateView):
    models = MainUser
    template_name = 'homepage/profile_tmp/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('homepage:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'homepage/profile_tmp/register_done.html'

def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'homepage/user_activation/bad_signature.html')
    user = get_object_or_404(MainUser, username=username)
    if user.is_activated:
        template = 'homepage/user_activation/user_is_activated.html'
    else:
        template = 'homepage/user_activation/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

templates/basic.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %} - Best Book Store Ever</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}">
        {% bootstrap_javascript jquery='slim' %}
</head>
<body>
    <div class="container">
        <h2>Best Book Store Ever</h2>
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
              <a class="p-2 text-muted" href="{% url 'homepage:index' %}">Главная</a>

              {% if user.is_authenticated %}
              <a class="p-2 text-muted" href="{% url 'homepage:profile' %}">Посты пользователя {{ user.username }}</a>
              {% else %}
              <a class="p-2 text-muted" href="{% url 'homepage:login' %}">Вход</a>
              <a class="p-2 text-muted" href="{% url 'homepage:register' %}">Регистрация</a>
              {% endif %}
              <a class="p-2 text-muted" href="{% url 'homepage:logout' %}">Выход</a>
              <a class="p-2 text-muted" href="{% url 'homepage:about' %}">Контакты</a>
            </nav>
          </div>
        {% block content %}
        {% endblock %}
    </div>



</body>
</html>

templates/homepage/about.html
{% extends 'basic.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>Контакты</h1>
        <p>Информация скрыта пока что</p>
    </div>
{% endblock %}

templates/homepage/product_page.html
{% extends 'basic.html' %}

{% block title%}Недавний пост{% endblock %}

{% block content %}

    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Title</h5>
        <h6 class="card-subtitle mb-2 text-muted">Second title</h6>
        <p class="card-text">Body</p>
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
      </div>
    </div>

{% endblock %}

templates/homepage/profile_tmp/change_user_info.html
{% extends 'basic.html' %}

{% load bootstrap4 %}

{% block title%}Изменение личных данных{% endblock %}

{% block content %}
    <h2>Изменение личных данных пользователя {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сохранить' %} {% endbuttons %}
    </form>
{% endblock %}

templates/homepage/profile_tmp/login.html
{% extends 'basic.html' %}
{% load bootstrap4 %}
{% block title%}Вход{% endblock%}

{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
    <p>Вход уже выполнен</p>
    {% else %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <input type="hidden" name="next" value="{{ next }}">
        {% buttons submit='Войти' %} {% endbuttons %}
    </form>
    {% endif%}
{% endblock %}

templates/homepage/profile_tmp/logout.html
{% extends 'basic.html' %}

{% block title%}Выход выполнен{% endblock %}

{% block content %}
    <h2>Выход</h2>
    <p>Выход выполнен успешно</p>
{% endblock %}

templates/homepage/profile_tmp/password_change.html
{% extends 'basic.html' %}

{% load bootstrap4 %}

{% block title%}Смена пароля{% endblock %}

{% block content %}
    <h2>Изменение пароля пользователя {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сохранить пароль' %} {% endbuttons %}
    </form>
{% endblock %}

templates/homepage/profile_tmp/profile.html
{% extends 'basic.html' %}

{% block title%}Профиль{% endblock %}

{% block content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    {% if user.first_name and user.last_name %}
    <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
    <p>Здравствуйте!</p>
    {% endif %}
    <h3>Ваши посты</h3>
    <a type="button" class="btn btn-primary" href="{% url 'homepage:profile_change' %}">Изменить личные данные</a>
    <a type="button" class="btn btn-primary" href="{% url 'homepage:password_change' %}">Изменить пароль</a>
{% endblock %}

templates/homepage/profile_tmp/register_done.html
{% extends 'basic.html' %}

{% block title%}Регистрация завершена{% endblock %}


{% block content %}
    <h2>Регистрация</h2>
    <p>Регистрация пользователя завершена.</p>
    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
{% endblock %}

templates/homepage/profile_tmp/register_user.html
{% extends 'basic.html' %}

{% load bootstrap4 %}

{% block title%}Регистрация{% endblock %}


{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Зарегестрироваться' %} {% endbuttons %}
    </form>
{% endblock %}

templates/homepage/user_activation/activation_done.html
{% extends 'basic.html' %}


{% block title%}Активация выполнена{% endblock %}


{% block content %}
    <h2>Активация</h2>
    <p>Пользователь с именем {{ user.username }} успешно активирован.</p>
    <p><a href="{% url 'homepage:login' %}">Вход на сайт</a></p>
{% endblock %}

templates/homepage/user_activation/bad_signature.html
{% extends 'basic.html' %}


{% block title%}Ошибка активации!{% endblock %}


{% block content %}
    <h2>Активация</h2>
    <p>Активация пользователя с таким именем прошла неудачно!</p>
    <p><a href="{% url 'homepage:register' %}">Повторить регистрацию?</a></p>
{% endblock %}

templates/homepage/user_activation/user_is_activated.html
{% extends 'basic.html' %}


{% block title%}Пользователь уже активирован{% endblock %}


{% block content %}
    <h2>Активация</h2>
    <p>Активация пользователя с таким именем невозможна. Пользователь уже существует.</p>
    <p><a href="{% url 'homepage:login' %}">Войти на сайт</a></p>
{% endblock %}